#Numpy (Numerical python) is powerful python library. used for numerical computing.

It support large multi dimensional arrays and matrices.
along with a collection  of mathematical function.

In [1]:
!pip install numpy

In [2]:
import numpy

In [4]:
import numpy as np
#as - alias - short name

#Array - arrangement of element in the form of dimensions.

1D - 1 dimension

2D - 2 dimension

3D - 3 dimension

In [5]:
arr = np.array([1,2,3,4,5,6,7,8])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

#array attributes

In [10]:
#.ndim - number of dimension

In [11]:
arr.ndim

1

In [12]:
arr1.ndim

2

In [16]:
#.shape   (rows,columns)

In [14]:
arr.shape

(8,)

In [17]:
arr1.shape

(2, 3)

In [18]:
#size - total no.of element

In [19]:
arr.size

8

In [20]:
arr1.size

6

In [21]:
#dtpye - data type

In [22]:
arr.dtype

dtype('int64')

In [23]:
arr1.dtype

dtype('int64')

#matrix

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

#indexing and slicing

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
arr[4]        #indexing - accessing one element

5

In [34]:
arr[0:4]      #slicing - accessing range of element

array([1, 2, 3, 4])

In [35]:
arr2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [36]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2[1,2]

6

In [39]:
arr2[1,2]

6

In [40]:
arr2[0:2 , 1:3]     #0:2 - 0 & 1st row // 1:3 1st and 2nd column

array([[2, 3],
       [5, 6]])

#reshaping and flatten

In [43]:
arr = np.array([1,2,3,4,5,6])

In [44]:
arr.size

6

In [45]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [49]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [55]:
arr3.size

12

In [56]:
arr3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr