In [1]:
import numpy as np

In [2]:
np.arange(5)      #ARRAY OF RANGE

array([0, 1, 2, 3, 4])

In [3]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [4]:
np.arange(2,9,2)  # 2,9 is range, last 2 is stepsize

array([2, 4, 6, 8])

In [5]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [8]:
arr = np.array([8,4,5,7,9,6,2,1,4,5,3])

In [9]:
np.sort(arr)

array([1, 2, 3, 4, 4, 5, 5, 6, 7, 8, 9])

In [10]:
arr.max()

9

In [11]:
arr.min()

1

In [14]:
arr.sum()

54

In [15]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.mean(arr)

4.909090909090909

In [18]:
np.median(arr)

5.0

In [22]:
from scipy import stats        #scientific python

In [23]:
stats.mode(arr)

ModeResult(mode=4, count=2)

In [24]:
np.var(arr)

5.537190082644629

In [26]:
np.std(arr)

2.3531234737354154

In [29]:
np.corrcoef(arr)

1.0

In [30]:
np.percentile(arr,25)

3.5

In [31]:
np.percentile(arr,50)

5.0

In [32]:
np.percentile(arr,75)

6.5

In [34]:
np.percentile(arr,75) - np.percentile(arr,25)

3.0

In [35]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

In [36]:
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [37]:
np.cov(x,y)

array([[ 2.5,  5. ],
       [ 5. , 10. ]])

In [40]:
np.random.randint(1,100,5)

array([53, 47, 66, 64, 83])

In [41]:
np.random.rand(5)        #by default range is 0 to 1

array([0.01953309, 0.54209234, 0.99252219, 0.70817731, 0.29114751])

In [42]:
np.random.randint(5)

2

In [45]:
np.random.randn(5)       #randn - normal distributiom, mean = 0, std = 1

array([-0.11447455, -0.91113217, -0.43297927, -0.54020986, -0.01273618])